// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "CloudFtpQuickstart")
public final class CloudFtpClient: Clients.CloudFtpProtocol, Sendable {
  let inner: any Clients.CloudFtpStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `CloudFtpClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudFtpStub = try Clients.CloudFtpTransport(options)
    inner = Clients.CloudFtpRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudFtpLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Servers in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_ListServers")
  public func listServers(
    request: ListServersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.ListServersResponse {
    try await self.inner.listServers(request: request, options: options)
  }

  /// Lists Servers in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_ListServers")
  public func listServers(
    byItem: ListServersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Server, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudFTPV1.ListServersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServers(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Server.
  ///
  /// @Snippet(path: "CloudFtp_GetServer")
  public func getServer(
    request: GetServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.Server {
    try await self.inner.getServer(request: request, options: options)
  }

  /// Creates a new Server in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_CreateServer")
  public func createServer(
    request: CreateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createServer(request: request, options: options)
  }

  /// Creates a new Server in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_CreateServer")
  public func createServer(
    withPolling: CreateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      return try op._extractStatus(Server.self)
    }
    let rawOp = try await self.createServer(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Server.
  ///
  /// @Snippet(path: "CloudFtp_UpdateServer")
  public func updateServer(
    request: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateServer(request: request, options: options)
  }

  /// Updates the parameters of a single Server.
  ///
  /// @Snippet(path: "CloudFtp_UpdateServer")
  public func updateServer(
    withPolling: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      return try op._extractStatus(Server.self)
    }
    let rawOp = try await self.updateServer(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Server.
  ///
  /// @Snippet(path: "CloudFtp_DeleteServer")
  public func deleteServer(
    request: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteServer(request: request, options: options)
  }

  /// Deletes a single Server.
  ///
  /// @Snippet(path: "CloudFtp_DeleteServer")
  public func deleteServer(
    withPolling: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteServer(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Users in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_ListUsers")
  public func listUsers(
    request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.ListUsersResponse {
    try await self.inner.listUsers(request: request, options: options)
  }

  /// Lists Users in a given project and location.
  ///
  /// @Snippet(path: "CloudFtp_ListUsers")
  public func listUsers(
    byItem: ListUsersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<User, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudFTPV1.ListUsersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listUsers(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single User.
  ///
  /// @Snippet(path: "CloudFtp_GetUser")
  public func getUser(
    request: GetUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.User {
    try await self.inner.getUser(request: request, options: options)
  }

  /// Creates a new User in a given project and location and Server.
  ///
  /// @Snippet(path: "CloudFtp_CreateUser")
  public func createUser(
    request: CreateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createUser(request: request, options: options)
  }

  /// Creates a new User in a given project and location and Server.
  ///
  /// @Snippet(path: "CloudFtp_CreateUser")
  public func createUser(
    withPolling: CreateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<User>.State
      in
      return try op._extractStatus(User.self)
    }
    let rawOp = try await self.createUser(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<User>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single User.
  ///
  /// @Snippet(path: "CloudFtp_UpdateUser")
  public func updateUser(
    request: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateUser(request: request, options: options)
  }

  /// Updates the parameters of a single User.
  ///
  /// @Snippet(path: "CloudFtp_UpdateUser")
  public func updateUser(
    withPolling: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<User>.State
      in
      return try op._extractStatus(User.self)
    }
    let rawOp = try await self.updateUser(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<User>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single User.
  ///
  /// @Snippet(path: "CloudFtp_DeleteUser")
  public func deleteUser(
    request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteUser(request: request, options: options)
  }

  /// Deletes a single User.
  ///
  /// @Snippet(path: "CloudFtp_DeleteUser")
  public func deleteUser(
    withPolling: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteUser(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Starts a stopping/stopped Server.
  ///
  /// @Snippet(path: "CloudFtp_StartServer")
  public func startServer(
    request: StartServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startServer(request: request, options: options)
  }

  /// Starts a stopping/stopped Server.
  ///
  /// @Snippet(path: "CloudFtp_StartServer")
  public func startServer(
    withPolling: StartServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      return try op._extractStatus(Server.self)
    }
    let rawOp = try await self.startServer(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Stops an active Server.
  ///
  /// @Snippet(path: "CloudFtp_StopServer")
  public func stopServer(
    request: StopServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.stopServer(request: request, options: options)
  }

  /// Stops an active Server.
  ///
  /// @Snippet(path: "CloudFtp_StopServer")
  public func stopServer(
    withPolling: StopServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      return try op._extractStatus(Server.self)
    }
    let rawOp = try await self.stopServer(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "CloudFtp_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "CloudFtp_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudFtp_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFtp_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFtp_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFtp_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFtp_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFtp_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudFtpClient`.
  ///
  /// To mock `CloudFtpClient` change your functions to receive
  /// `some CloudFtpProtocol` or `any CloudFtpProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudFtpProtocol {
    /// See `CloudFtpClient.listServers`.
    func listServers(request: ListServersRequest) async throws
      -> GoogleCloudFTPV1.ListServersResponse

    /// See `CloudFtpClient.listServers`.
    func listServers(
      byItem: ListServersRequest
    ) throws -> any AsyncSequence<Server, Swift.Error>

    /// See `CloudFtpClient.listServers`.
    func listServers(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Server, Swift.Error>

    /// See `CloudFtpClient.getServer`.
    func getServer(request: GetServerRequest) async throws -> GoogleCloudFTPV1.Server

    /// See `CloudFtpClient.getServer`.
    func getServer(
      name: Swift.String,
    ) async throws -> GoogleCloudFTPV1.Server

    /// See `CloudFtpClient.createServer`.
    func createServer(request: CreateServerRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.createServer`.
    func createServer(withPolling: CreateServerRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Server>

    /// See `CloudFtpClient.createServer`.
    func createServer(
      parent: Swift.String,
      server: Server?,
      serverId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.updateServer`.
    func updateServer(request: UpdateServerRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.updateServer`.
    func updateServer(withPolling: UpdateServerRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Server>

    /// See `CloudFtpClient.updateServer`.
    func updateServer(
      server: Server?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.deleteServer`.
    func deleteServer(request: DeleteServerRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.deleteServer`.
    func deleteServer(withPolling: DeleteServerRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `CloudFtpClient.deleteServer`.
    func deleteServer(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudFtpClient.listUsers`.
    func listUsers(request: ListUsersRequest) async throws -> GoogleCloudFTPV1.ListUsersResponse

    /// See `CloudFtpClient.listUsers`.
    func listUsers(
      byItem: ListUsersRequest
    ) throws -> any AsyncSequence<User, Swift.Error>

    /// See `CloudFtpClient.listUsers`.
    func listUsers(
      parent: Swift.String,
    ) throws -> any AsyncSequence<User, Swift.Error>

    /// See `CloudFtpClient.getUser`.
    func getUser(request: GetUserRequest) async throws -> GoogleCloudFTPV1.User

    /// See `CloudFtpClient.getUser`.
    func getUser(
      name: Swift.String,
    ) async throws -> GoogleCloudFTPV1.User

    /// See `CloudFtpClient.createUser`.
    func createUser(request: CreateUserRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.createUser`.
    func createUser(withPolling: CreateUserRequest) async throws -> any GoogleCloudGax
      .PollableOperation<User>

    /// See `CloudFtpClient.createUser`.
    func createUser(
      parent: Swift.String,
      user: User?,
      userId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<User>

    /// See `CloudFtpClient.updateUser`.
    func updateUser(request: UpdateUserRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.updateUser`.
    func updateUser(withPolling: UpdateUserRequest) async throws -> any GoogleCloudGax
      .PollableOperation<User>

    /// See `CloudFtpClient.updateUser`.
    func updateUser(
      user: User?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<User>

    /// See `CloudFtpClient.deleteUser`.
    func deleteUser(request: DeleteUserRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.deleteUser`.
    func deleteUser(withPolling: DeleteUserRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `CloudFtpClient.deleteUser`.
    func deleteUser(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudFtpClient.startServer`.
    func startServer(request: StartServerRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.startServer`.
    func startServer(withPolling: StartServerRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Server>

    /// See `CloudFtpClient.startServer`.
    func startServer(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.stopServer`.
    func stopServer(request: StopServerRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.stopServer`.
    func stopServer(withPolling: StopServerRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Server>

    /// See `CloudFtpClient.stopServer`.
    func stopServer(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudFtpClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudFtpClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `CloudFtpClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudFtpClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFtpClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFtpClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `CloudFtpClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudFtpClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `CloudFtpClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudFtpClient.listServers`.
    func listServers(
      request: ListServersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFTPV1.ListServersResponse

    /// See `CloudFtpClient.listServers`.
    func listServers(
      byItem: ListServersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Server, Swift.Error>

    /// See `CloudFtpClient.getServer`.
    func getServer(
      request: GetServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFTPV1.Server

    /// See `CloudFtpClient.createServer`.
    func createServer(
      request: CreateServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.createServer`.
    func createServer(
      withPolling: CreateServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.updateServer`.
    func updateServer(
      request: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.updateServer`.
    func updateServer(
      withPolling: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.deleteServer`.
    func deleteServer(
      request: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.deleteServer`.
    func deleteServer(
      withPolling: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudFtpClient.listUsers`.
    func listUsers(
      request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFTPV1.ListUsersResponse

    /// See `CloudFtpClient.listUsers`.
    func listUsers(
      byItem: ListUsersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<User, Swift.Error>

    /// See `CloudFtpClient.getUser`.
    func getUser(
      request: GetUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFTPV1.User

    /// See `CloudFtpClient.createUser`.
    func createUser(
      request: CreateUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.createUser`.
    func createUser(
      withPolling: CreateUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<User>

    /// See `CloudFtpClient.updateUser`.
    func updateUser(
      request: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.updateUser`.
    func updateUser(
      withPolling: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<User>

    /// See `CloudFtpClient.deleteUser`.
    func deleteUser(
      request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.deleteUser`.
    func deleteUser(
      withPolling: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudFtpClient.startServer`.
    func startServer(
      request: StartServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.startServer`.
    func startServer(
      withPolling: StartServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.stopServer`.
    func stopServer(
      request: StopServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFtpClient.stopServer`.
    func stopServer(
      withPolling: StopServerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Server>

    /// See `CloudFtpClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudFtpClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudFtpClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CloudFtpClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudFtpClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFtpClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `CloudFtpClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudFtpProtocol {
  public func listServers(request: ListServersRequest) async throws
    -> GoogleCloudFTPV1.ListServersResponse
  {
    try await self.listServers(request: request, options: .init())
  }

  public func listServers(
    request: ListServersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.ListServersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listServers(
    byItem: ListServersRequest
  ) throws -> any AsyncSequence<Server, Swift.Error> {
    try self.listServers(byItem: byItem, options: .init())
  }

  public func listServers(
    byItem: ListServersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Server, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudFTPV1.ListServersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listServers(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Server, Swift.Error> {
    let request = ListServersRequest().with {
      $0.parent = parent
    }
    return try self.listServers(byItem: request)
  }

  public func getServer(request: GetServerRequest) async throws -> GoogleCloudFTPV1.Server {
    try await self.getServer(request: request, options: .init())
  }

  public func getServer(
    request: GetServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.Server {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getServer(
    name: Swift.String,
  ) async throws -> GoogleCloudFTPV1.Server {
    let request = GetServerRequest().with {
      $0.name = name
    }
    return try await self.getServer(request: request)
  }

  public func createServer(request: CreateServerRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createServer(request: request, options: .init())
  }

  public func createServer(
    request: CreateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createServer(withPolling: CreateServerRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Server>
  {
    try await self.createServer(withPolling: withPolling, options: .init())
  }

  public func createServer(
    withPolling: CreateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createServer(
    parent: Swift.String,
    server: Server?,
    serverId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let request = CreateServerRequest().with {
      $0.parent = parent
      $0.server = server
      $0.serverId = serverId
    }
    return try await self.createServer(withPolling: request)
  }

  public func updateServer(request: UpdateServerRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateServer(request: request, options: .init())
  }

  public func updateServer(
    request: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateServer(withPolling: UpdateServerRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Server>
  {
    try await self.updateServer(withPolling: withPolling, options: .init())
  }

  public func updateServer(
    withPolling: UpdateServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateServer(
    server: Server?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let request = UpdateServerRequest().with {
      $0.server = server
      $0.updateMask = updateMask
    }
    return try await self.updateServer(withPolling: request)
  }

  public func deleteServer(request: DeleteServerRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteServer(request: request, options: .init())
  }

  public func deleteServer(
    request: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteServer(withPolling: DeleteServerRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteServer(withPolling: withPolling, options: .init())
  }

  public func deleteServer(
    withPolling: DeleteServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteServer(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteServerRequest().with {
      $0.name = name
    }
    return try await self.deleteServer(withPolling: request)
  }

  public func listUsers(request: ListUsersRequest) async throws
    -> GoogleCloudFTPV1.ListUsersResponse
  {
    try await self.listUsers(request: request, options: .init())
  }

  public func listUsers(
    request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.ListUsersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listUsers(
    byItem: ListUsersRequest
  ) throws -> any AsyncSequence<User, Swift.Error> {
    try self.listUsers(byItem: byItem, options: .init())
  }

  public func listUsers(
    byItem: ListUsersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<User, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudFTPV1.ListUsersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsers(
    parent: Swift.String,
  ) throws -> any AsyncSequence<User, Swift.Error> {
    let request = ListUsersRequest().with {
      $0.parent = parent
    }
    return try self.listUsers(byItem: request)
  }

  public func getUser(request: GetUserRequest) async throws -> GoogleCloudFTPV1.User {
    try await self.getUser(request: request, options: .init())
  }

  public func getUser(
    request: GetUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFTPV1.User {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getUser(
    name: Swift.String,
  ) async throws -> GoogleCloudFTPV1.User {
    let request = GetUserRequest().with {
      $0.name = name
    }
    return try await self.getUser(request: request)
  }

  public func createUser(request: CreateUserRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createUser(request: request, options: .init())
  }

  public func createUser(
    request: CreateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createUser(withPolling: CreateUserRequest) async throws -> any GoogleCloudGax
    .PollableOperation<User>
  {
    try await self.createUser(withPolling: withPolling, options: .init())
  }

  public func createUser(
    withPolling: CreateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<User>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createUser(
    parent: Swift.String,
    user: User?,
    userId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let request = CreateUserRequest().with {
      $0.parent = parent
      $0.user = user
      $0.userId = userId
    }
    return try await self.createUser(withPolling: request)
  }

  public func updateUser(request: UpdateUserRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateUser(request: request, options: .init())
  }

  public func updateUser(
    request: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateUser(withPolling: UpdateUserRequest) async throws -> any GoogleCloudGax
    .PollableOperation<User>
  {
    try await self.updateUser(withPolling: withPolling, options: .init())
  }

  public func updateUser(
    withPolling: UpdateUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<User>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateUser(
    user: User?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<User> {
    let request = UpdateUserRequest().with {
      $0.user = user
      $0.updateMask = updateMask
    }
    return try await self.updateUser(withPolling: request)
  }

  public func deleteUser(request: DeleteUserRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteUser(request: request, options: .init())
  }

  public func deleteUser(
    request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteUser(withPolling: DeleteUserRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteUser(withPolling: withPolling, options: .init())
  }

  public func deleteUser(
    withPolling: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteUser(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteUserRequest().with {
      $0.name = name
    }
    return try await self.deleteUser(withPolling: request)
  }

  public func startServer(request: StartServerRequest) async throws -> GoogleLongRunning.Operation {
    try await self.startServer(request: request, options: .init())
  }

  public func startServer(
    request: StartServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func startServer(withPolling: StartServerRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Server>
  {
    try await self.startServer(withPolling: withPolling, options: .init())
  }

  public func startServer(
    withPolling: StartServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func startServer(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let request = StartServerRequest().with {
      $0.name = name
    }
    return try await self.startServer(withPolling: request)
  }

  public func stopServer(request: StopServerRequest) async throws -> GoogleLongRunning.Operation {
    try await self.stopServer(request: request, options: .init())
  }

  public func stopServer(
    request: StopServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func stopServer(withPolling: StopServerRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Server>
  {
    try await self.stopServer(withPolling: withPolling, options: .init())
  }

  public func stopServer(
    withPolling: StopServerRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Server>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func stopServer(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Server> {
    let request = StopServerRequest().with {
      $0.name = name
    }
    return try await self.stopServer(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
