// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for external server.
public struct ExternalServerConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. IP address of the LB via which clients will connect.
  public var ipAddress: Swift.String = Swift.String()

  /// Optional. List of CIDR blocks that are allowed to access the Server.
  /// A CIDR range consists of an IP Address and a prefix length to construct the
  /// subnet mask. By default, the prefix length is 32 (i.e. matches a single IP
  /// address). For now, only IPV4 addresses are supported.
  /// Examples: "203.0.113.0/24" -
  /// matches with the IP addresses in the range 203.0.113.0 - 203.0.113.255.
  /// "0.0.0.0/0" - matches against any IP address.
  /// This field must contain at least one entry if the access type is EXTERNAL.
  /// The number of allowed CIDR blocks cannot exceed 500.
  /// Example: 192.168.0.0/16
  public var allowedCidrBlocks: [Swift.String] = []

  /// Initialize a new instance of `ExternalServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExternalServerConfig().with { $0.ipAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.ExternalServerConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
