// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration for external server.
public struct ExternalServerConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. IP address of the LB via which clients will connect.
  public var ipAddress: Swift.String = Swift.String()

  /// Optional. List of CIDR blocks that are allowed to access the Server.
  /// A CIDR range consists of an IP Address and a prefix length to construct the
  /// subnet mask. By default, the prefix length is 32 (i.e. matches a single IP
  /// address). For now, only IPV4 addresses are supported.
  /// Examples: "203.0.113.0/24" -
  /// matches with the IP addresses in the range 203.0.113.0 - 203.0.113.255.
  /// "0.0.0.0/0" - matches against any IP address.
  /// This field must contain at least one entry if the access type is EXTERNAL.
  /// The number of allowed CIDR blocks cannot exceed 500.
  /// Example: 192.168.0.0/16
  public var allowedCidrBlocks: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExternalServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExternalServerConfig().with { $0.ipAddress = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ipAddress = CodingKeys(stringValue: "ipAddress")
    static let allowedCidrBlocks = CodingKeys(stringValue: "allowedCidrBlocks")

    static let _knownKeys: Set<Swift.String> = [
      "ipAddress",
      "allowedCidrBlocks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress) {
      self.ipAddress = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .allowedCidrBlocks) {
      self.allowedCidrBlocks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ipAddress, forKey: .ipAddress)
    try container.encode(self.allowedCidrBlocks, forKey: .allowedCidrBlocks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.ExternalServerConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
