// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for private server accessible via PSC.
public struct InternalServerConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the service attachment.
  /// Format:
  /// `projects/{project}/regions/{region}/serviceAttachments/{service_attachment}`
  public var serviceAttachment: Swift.String = Swift.String()

  /// Required. A list of projects that are permitted to connect.
  /// At least one project is required in the allow list.
  public var consumerAcceptList: [InternalServerConfig.AllowedConsumer] = []

  /// Optional. A list of projects that are denied connection.
  /// Format: "projects/sample_project_id" or "projects/1234567890"
  /// Projects in this list will be denied access, even if they are included in
  /// the `allow_list`. If this list is empty, no projects are explicitly
  /// rejected.
  public var consumerRejectList: [InternalServerConfig.DeniedConsumer] = []

  /// Output only. Details of endpoints created by the customer.
  public var pscEndpoints: [InternalServerConfig.PscEndpoint] = []

  /// Initialize a new instance of `InternalServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InternalServerConfig().with { $0.serviceAttachment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A consumer project or network that is permitted to connect to the server
  /// via PSC.
  public struct AllowedConsumer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The connection limit for the consumer.
    /// Value must be greater than 0.
    public var connectionLimit: Swift.Int64 = Swift.Int64()

    /// Required. Specifies the type of consumer.
    public var consumerType: OneOf_ConsumerType? = nil

    /// Initialize a new instance of `AllowedConsumer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AllowedConsumer().with { $0.project = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case project = "project"
      case connectionLimit = "connectionLimit"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.connectionLimit = try container.decode(Swift.Int64.self, forKey: .connectionLimit)

      var consumerType: OneOf_ConsumerType? = nil
      let consumerTypeCheckAndSet = {
        if consumerType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'consumerType'"))
        }
        consumerType = $0
      }
      if let project = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        try consumerTypeCheckAndSet(.project(project))
      }
      self.consumerType = consumerType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.connectionLimit, forKey: .connectionLimit)

      if let choice = self.consumerType {
        switch choice {
        case .project(let value):
          try container.encode(value, forKey: .project)
        }
      }
    }

    /// Required. Specifies the type of consumer.
    public enum OneOf_ConsumerType: Codable, Equatable, Sendable {
      /// The project ID or number of the consumer project.
      /// Must be in the format: `projects/{project}`.
      case project(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ftp.v1.InternalServerConfig.AllowedConsumer"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A consumer project or network that is denied to connect to the server via
  /// PSC.
  public struct DeniedConsumer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Specifies the type of consumer.
    public var consumerType: OneOf_ConsumerType? = nil

    /// Initialize a new instance of `DeniedConsumer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeniedConsumer().with { $0.project = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case project = "project"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var consumerType: OneOf_ConsumerType? = nil
      let consumerTypeCheckAndSet = {
        if consumerType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'consumerType'"))
        }
        consumerType = $0
      }
      if let project = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
        try consumerTypeCheckAndSet(.project(project))
      }
      self.consumerType = consumerType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.consumerType {
        switch choice {
        case .project(let value):
          try container.encode(value, forKey: .project)
        }
      }
    }

    /// Required. Specifies the type of consumer.
    public enum OneOf_ConsumerType: Codable, Equatable, Sendable {
      /// The project ID or number of the consumer project.
      /// Must be in the format: `projects/{project}`.
      case project(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ftp.v1.InternalServerConfig.DeniedConsumer"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Details of PSC endpoint created by customer.
  public struct PscEndpoint: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. This is a Resource name for Private Service Connect
    /// endpoint. Format:
    /// `projects/{project}/regions/{region}/forwardingRules/{forwarding_rule}`
    public var endpoint: Swift.String = Swift.String()

    /// Output only. The consumer network.
    /// Format: `projects/{project}/locations/{location}/networks/{network}`
    public var network: Swift.String = Swift.String()

    /// Output only. The status of the connected endpoint.
    public var status: Swift.String = Swift.String()

    /// Initialize a new instance of `PscEndpoint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PscEndpoint().with { $0.endpoint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.ftp.v1.InternalServerConfig.PscEndpoint"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.InternalServerConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
