// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents credentials of an FTP Server.
public struct ServerCredential: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The fingerprint is a hash of the public key, and is displayed
  /// when clients access the server for the first time to verify the server's
  /// identity.
  public var fingerprint: Swift.String = Swift.String()

  /// Output only. Asymmetric algorithm used by the public key.
  /// Possible values (can be expanded in future):
  /// - ssh-ed25519
  public var asymmetricAlgorithm: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServerCredential`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServerCredential().with { $0.fingerprint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fingerprint = CodingKeys(stringValue: "fingerprint")
    static let asymmetricAlgorithm = CodingKeys(stringValue: "asymmetricAlgorithm")

    static let _knownKeys: Set<Swift.String> = [
      "fingerprint",
      "asymmetricAlgorithm",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fingerprint) {
      self.fingerprint = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .asymmetricAlgorithm) {
      self.asymmetricAlgorithm = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fingerprint, forKey: .fingerprint)
    try container.encode(self.asymmetricAlgorithm, forKey: .asymmetricAlgorithm)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.ServerCredential"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
