// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing Server object
public struct Server: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Display name of the Server
  public var displayName: Swift.String = Swift.String()

  /// Required. The access type of the Server.
  public var accessType: Server.AccessType = Server.AccessType()

  /// Output only. The state of the server.
  public var state: Server.State = Server.State()

  /// Output only. Credentials of the FTP Server.
  public var googleManagedServerCredential: ServerCredential? = nil

  /// Output only. Service agent used to access the customer bucket.
  public var serviceAgent: Swift.String = Swift.String()

  /// Configuration for server access.
  /// If this is set, it must match the value in the `access_type` field.
  public var accessConfig: OneOf_AccessConfig? = nil

  /// Initialize a new instance of `Server`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Server().with { $0.externalConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case externalConfig = "externalConfig"
    case internalConfig = "internalConfig"
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case displayName = "displayName"
    case accessType = "accessType"
    case state = "state"
    case googleManagedServerCredential = "googleManagedServerCredential"
    case serviceAgent = "serviceAgent"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.accessType = try container.decode(Server.AccessType.self, forKey: .accessType)
    self.state = try container.decode(Server.State.self, forKey: .state)
    self.googleManagedServerCredential = try container.decodeIfPresent(
      ServerCredential.self, forKey: .googleManagedServerCredential)
    self.serviceAgent = try container.decode(Swift.String.self, forKey: .serviceAgent)

    var accessConfig: OneOf_AccessConfig? = nil
    let accessConfigCheckAndSet = {
      if accessConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'accessConfig'"))
      }
      accessConfig = $0
    }
    if let externalConfig = try container.decodeIfPresent(
      ExternalServerConfig?.self, forKey: .externalConfig)
    {
      try accessConfigCheckAndSet(.externalConfig(externalConfig))
    }
    if let internalConfig = try container.decodeIfPresent(
      InternalServerConfig?.self, forKey: .internalConfig)
    {
      try accessConfigCheckAndSet(.internalConfig(internalConfig))
    }
    self.accessConfig = accessConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.accessType, forKey: .accessType)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.googleManagedServerCredential, forKey: .googleManagedServerCredential)
    try container.encode(self.serviceAgent, forKey: .serviceAgent)

    if let choice = self.accessConfig {
      switch choice {
      case .externalConfig(let value):
        try container.encode(value, forKey: .externalConfig)
      case .internalConfig(let value):
        try container.encode(value, forKey: .internalConfig)
      }
    }
  }

  /// The access type of the Server.
  public enum AccessType: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Server is assigned a public IP.
    case external
    /// Server is assigned an internal IP.
    case `internal`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .external: return 1
      case .`internal`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCESS_TYPE_UNSPECIFIED"
      case .external: return "EXTERNAL"
      case .`internal`: return "INTERNAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccessType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCESS_TYPE_UNSPECIFIED": self = .unspecified
      case "EXTERNAL": self = .external
      case "INTERNAL": self = .`internal`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccessType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .external
      case 2: self = .`internal`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .external: return try container.encode(1)
      case .`internal`: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Tracks Server status.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Server is being created.
    case creating
    /// Server is starting.
    case starting
    /// Server is ready to be used.
    case active
    /// Server is stopping.
    case stopping
    /// Server is stopped.
    case stopped
    /// Server is being deleted.
    case deleting
    /// Server is in error state.
    case error
    /// Server is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .starting: return 2
      case .active: return 3
      case .stopping: return 4
      case .stopped: return 5
      case .deleting: return 6
      case .error: return 7
      case .updating: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .starting: return "STARTING"
      case .active: return "ACTIVE"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "STARTING": self = .starting
      case "ACTIVE": self = .active
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .starting
      case 3: self = .active
      case 4: self = .stopping
      case 5: self = .stopped
      case 6: self = .deleting
      case 7: self = .error
      case 8: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .starting: return try container.encode(2)
      case .active: return try container.encode(3)
      case .stopping: return try container.encode(4)
      case .stopped: return try container.encode(5)
      case .deleting: return try container.encode(6)
      case .error: return try container.encode(7)
      case .updating: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Configuration for server access.
  /// If this is set, it must match the value in the `access_type` field.
  public enum OneOf_AccessConfig: Codable, Equatable, Sendable {
    /// Configuration for external access.
    indirect case externalConfig(ExternalServerConfig?)
    /// Configuration for internal access.
    indirect case internalConfig(InternalServerConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.Server"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
