// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Mapping of backing Cloud Storage path to the directory where the user lands
/// in the SFTP server. If directory is not specified, it'll default to '/'.
///
/// Eg 1 -
/// (bucket_name: bucket, bucket_prefix: path1/path2, directory:
/// /abc/def/username)
///
/// The user will land at /abcd/def/username, and the view there will match that
/// of /bucket/path1/path2. The user will not be aware of Cloud Storage prefix
/// '/bucket/path1' and there will be no such directory in the view.
///
/// Eg 2 -
/// (bucket_name: bucket, bucket_prefix: path1/path2, directory: '')
///
/// The user will land at '/', and the view there will match
/// that of /bucket/path1/path2. The user will not be aware of Cloud Storage
/// prefix '/bucket/path1/path2' and there will be no such directory in the view.
public struct StorageDirectoryMapping: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the bucket.
  public var bucket: Swift.String = Swift.String()

  /// Optional. Prefix inside the bucket.
  public var bucketPrefix: Swift.String = Swift.String()

  /// Required. Directory where the user lands in the SFTP server.
  public var directory: Swift.String = Swift.String()

  /// Required. Permission to the bucket.
  public var permission: StorageDirectoryMapping.Permission = StorageDirectoryMapping.Permission()

  /// Initialize a new instance of `StorageDirectoryMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageDirectoryMapping().with { $0.bucket = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Tracks read/write access to the bucket.
  public enum Permission: Codable, Equatable, Sendable {
    /// Permission unspecified.
    case unspecified
    /// Read only permission.
    case readOnly
    /// Read write permission.
    case readWrite
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .readOnly: return 1
      case .readWrite: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PERMISSION_UNSPECIFIED"
      case .readOnly: return "READ_ONLY"
      case .readWrite: return "READ_WRITE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Permission/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PERMISSION_UNSPECIFIED": self = .unspecified
      case "READ_ONLY": self = .readOnly
      case "READ_WRITE": self = .readWrite
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Permission/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .readOnly
      case 2: self = .readWrite
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .readOnly: return try container.encode(1)
      case .readWrite: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.ftp.v1.StorageDirectoryMapping"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
